### ISSUE TITLE
Submit Restaurant Reviews

### ISSUE THREAD

**Issue by rudimusmaximus** [rudimusmaximus/FENDp5#1]
**_objective / purpose_**  

**_completion checklist_**
- [x] DevFlow and setup complete; can gulp to live edit via Browsersync with linting via cli and sass support
- [x] Update provided code to comply with most important linting requirements extended to google style
- [x] Responsive design specs met (see design) - satisfied with approach, used scss, minimal flex , and separated responsive scss
- [x] A11y specifications met (see design)
- [x] Offline capable via service worker cache for visited pages (see design)
- [x] Developer Tested - Test Copies (Disposable Alpha "DA!s" and Release Candidate)

POST LIVE:
- [x] Works on mobile and tablets
- [x] Accepted by Udacity reviewer

**_full pipeline documentation_**
---
# Overview - describe with history and related items  
# Solution Design  
Course requirements Feed Reader Testing [Project Rubric](https://review.udacity.com/#!/rubrics/1090/view)

# What's New Entry  
n/a
# Solution Implementation Notes  
During testing and moving to github pages hosting, there were images that would not load.
Tried a number of approaches. Finally, updated relative paths and other path-link creation to work if in "production" on github hosting under https or locally on http.
